### ISSUE TITLE
导出excel文件时，以0开头的字符串会默认变成数字格式，导致数据丢失

### ISSUE THREAD

**Issue by wangye19920128** [x-extends/vxe-table-plugin-export-xlsx#24]
### 可复现的链接：

无

### 问题描述与截图：

数据中有以0开头的字符串，长度在6位，导出文件时，会默认存储为数字格式，导致数据丢失

### 操作系统：

window 11

### 浏览器版本：

edge 103.0.1264.62 (正式版本) (64 位) 

### vue 版本：

3.2.37

### vxe-table 版本：

4.2.8

**Comment by Johnwei386** [comment]
使用npm安装vxe-table-plugin-export-xlsx插件后，在node_modules的对应插件目录下，找到dist/index.common.js文件，在这个文件中，找到getCellLabel方法，将此方法中switch分支中的default分支修改为`return _xeUtils["default"].toString(cellValue);`

**Comment by wangye19920128** [comment]
没有成功，导出的表格开始去掉了字符串第一位的0

发自我的iPhone

**Comment by ooolize** [comment]
vex-table里 修改单元格值类型  columns.cellType = "string";  可以解决

**Comment by wangye19920128** [comment]
解决了解决了，感谢大佬，是我文档没看仔细。还有请教一下大佬，vxe-gird在使用的时候，列设置了fixed之后，宽度出现拖动条，然后用鼠标拖选fixed列的内容拖到没有设置fixed列内容时候就会出现单元格内容消失；还有一个表尾，设置了fixed之后表尾的格式全部崩，这个情况在分页设置成pagesizes=1000和-1的时候，数据量大出现了。

发自我的iPhone
